# Generated by Django 3.0.3 on 2020-04-04 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=25)),
                ('work', models.TextField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('type_house', models.CharField(max_length=25)),
                ('tel', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.SmallIntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('age', models.SmallIntegerField()),
                ('tel', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('Fe', 'Female')], max_length=2)),
                ('class_room', models.CharField(max_length=6)),
                ('stu_no', models.SmallIntegerField()),
                ('track', models.CharField(max_length=25)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('stu_code', models.CharField(max_length=5, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Parent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Regis_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('check_type', models.CharField(choices=[('IN', 'in'), ('OUT', 'out')], max_length=3)),
                ('score', models.SmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teach_course',
            field=models.ManyToManyField(to='school.Teacher'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('score_percent', models.SmallIntegerField()),
                ('session', models.SmallIntegerField()),
                ('enroll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Enroll')),
            ],
        ),
    ]
