# Generated by Django 3.0.5 on 2020-04-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tea_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tel',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
