# Generated by Django 3.0.3 on 2020-04-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200405_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent',
            new_name='parent_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teacher_id',
        ),
    ]
