# Generated by Django 3.0.5 on 2020-04-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='weekday',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('Su', 'Sunday')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
