# Generated by Django 3.0.5 on 2020-04-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200406_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regis_school',
            name='check_type',
            field=models.BooleanField(),
        ),
    ]
